services:
  app:
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - nodemodules:/app/node_modules
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos

  mysql:
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

volumes:
  todo-mysql-data:
  nodemodules:
